third_line

diff --git a/0x02-shell_redirections/6-third_line b/0x02-shell_redirections/6-third_line
--- a/0x02-shell_redirections/6-third_line
+++ b/0x02-shell_redirections/6-third_line
@@ -1,2 +1,16 @@
 #!/bin/bash
-head -n 3 iacta
+
+# Read the file line by line, and print the third line
+count=1
+while IFS='' read -r line || [[ -n "$line" ]]; do
+    if [ $count -eq 3 ]; then
+        echo $line
+        exit 0
+    fi
+    count=$((count+1))
+done < "iacta"
+
+# If the file has less than 3 lines, print an error message
+echo "Error: The file 'iacta' has less than 3 lines." >&2
+exit 1
+
